import { PoliciesTypes } from '@/types/policies-types';

export const privacyPolicyData: PoliciesTypes = {
  title: 'Privacy Policy',
  points: [
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Welcome to Ecocrew’s Privacy Policy</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew is a platform where business entities facilitate the sale of paper, plastic, metal & electronic scrap materials. Ecocrew understands the importance of privacy and also the importance of maintaining the confidentiality of personal information. Our Privacy Policy is applied to all the products and services which are being provided by us, and also sets out how we may collect, disclose and use the personal information (name, address, localization, etc.) of users. Users may use our services and products via Mobile Application.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Collection of Information:</h2>',
    '<div class="policiesSubDiv gap-3 md:gap-5">',
    '<p class="text-darkLow text-ecoStore leading-5">Your privacy is important to us and we have taken steps to ensure that we don\'t collect more information from you than is necessary for you to utilise our services and to protect your account.</p>',
    '<p class="text-darkLow text-ecoStore leading-5">We may collect your personal information at the time of registration like- name, address, mobile number, phone number, and also the location of the user on the Website or Mobile Application.</p>',
    '<p class="text-darkLow text-ecoStore leading-5">We record & maintain the activities which are being performed by the users on the platform.</p>',
    '<p class="text-darkLow text-ecoStore leading-5">During the registration users need to provide the mandatory information in certain categories like- business data (registration information, account information, etc.) or personal data (name, contact number, address, etc. If the user does not provide the mandatory information then we may not be able to complete the process of registration and then we will also not be able to deliver our services to the users.</p>',
    '</div>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Use of Personal Data:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">If the user is providing us any Personal Data then that means the user is giving us rights to use their information for the following purposes:</p>',
    '<ol class="policiesPointsDiv gap-3 md:gap-5">',
    '<li class="text-darkLow text-ecoStore leading-5">Verifying the identity of users.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">Verifying the eligibility to register as a user.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">This registration will provide you a user ID for our site and our site will maintain and manage your registration.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">We will provide you a customer service that will respond to your queries, feedback, claims, or disputes.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">Facilitating the communication between buyers and sellers on the Site.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">We may use your name, phone number, residential address, and email address (all marketing data) to provide notices, surveys, product alerts, communications, and other marketing materials to you relating to goods and services which are offered by us on the Site by an opt-in mechanism in which by clicking into the checkbox you give us your consent for your personal data and if you don\'t want to provide us your personal data you can use opt-out mechanism in which you can withdraw your consent.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">This disclosure is being done as it may be required for any of the above purposes or as required by law or in respect of any claims or potential claims brought against us.</li>',
    '</ol>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Disclosure of Personal Data:</h2>',
    '<ol class="policiesPointsDiv gap-3 md:gap-5">',
    '<li class="text-darkLow text-ecoStore leading-5">When necessary, we may also disclose and transfer users Personal Data to our professional advisers, law enforcement agencies, insurers, government, and other organisations.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">Any Personal Data supplied by the user will be retained by us and will be accessible by our employees, any Service Providers engaged by us, and third parties.</li>',
    "<li class=\"text-darkLow text-ecoStore leading-5\">We may share the user's Account Information with banks to enable the user's transactions to determine the user's credit worthiness and, in the process of such determination; we may need to make such Account Information available to banks or credit agencies.</li>",
    '<li class="text-darkLow text-ecoStore leading-5">We have implemented security controls and associated procedures to keep your Account Information and other Personal Data secure from malicious users or intruders. These controls provide a reasonable assurance that the minimum security requirements are in place. These controls do not guarantee that such controls can eliminate all of the risks of data- theft, data loss, or misuse of data.</li>',
    '</ol>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Cookies:</h2>',
    "<p class=\"text-darkLow text-ecoStore leading-5\">We use â€œcookiesâ€ to store specific information about users and also track the user's visits to the Site. A â€œcookieâ€ is a small amount of data that is sent to the user's browser and stored on the user's system hard drive. A cookie can be sent to the user's system hard drive only if the user will access the site using that system. If the user does not deactivate or erase the cookie, each time the user uses the same computer to access the Site, our web servers will be notified of the user's visit to the Site and in turn, we may have knowledge of the user's visit and the pattern of your usage. Generally, we use cookies to identify users and also enable us to:</p>",
    '<ol class="policiesPointsDiv gap-3 md:gap-5">',
    '<li class="text-darkLow text-ecoStore leading-5">Access user Registration Information or</li>',
    '<li class="text-darkLow text-ecoStore leading-5">Account Information because of which users do not have to re-enter it.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">Assist our partners to track user visits to the Site and process bids.</li>',
    '<li class="text-darkLow text-ecoStore leading-5">To track the progress.</li>',
    '</ol>',
    '<p class="text-darkLow text-ecoStore leading-5">Users can determine if and how a cookie will be accepted by organising the browser that is installed in the system user is using to access the Site. By setting up the preferences in the browser, the user can accept all cookies or choose to be notified when a cookie is sent or choose to reject all cookies. If the user rejects all cookies by choosing the cookie-disabling function in their own browser then the user may be required to re-enter information on the platform more often and certain features of the platform may be unavailable.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Minors:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew\'s mobile application and its contents are not targeted at minors (those under the age of 18) and we do not intend to sell any of our products or services to minors. However, we have no way of distinguishing the age of individuals who access our platform. If a minor has provided us with personal information without parental or guardian consent, the parent or guardian should contact our Legal Department at the email address given below to remove the information. Email ID: support@ecocrew.com</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Security Measures:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">We provide reasonable security to prevent unauthorised access to the platform, for maintaining the accuracy of the data, and to ensure the correct use of the information we hold. For registered users, your Registration Information and Account Information (if any) can be viewed and edited through your account. Our personnel will never ask you for your details in an unsolicited phone call or in an unsolicited email. No data transmission over the Internet or any wireless network can be guaranteed to be perfectly secure. As a result, while we try to protect the information we hold for you, we cannot guarantee the security of any information you transmit to us and you do so at your own risk.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Changes to this Privacy Policy:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Any changes to this Privacy Policy will be communicated by us posting an amended and restated Privacy Policy on the platform. You agree that any information we hold will be governed by the latest version of the Privacy Policy.</p>',
    '</div>',
  ].join(''),
};
