import { PoliciesTypes } from '@/types/policies-types';

export const termsAndConditonsData: PoliciesTypes = {
  title: 'Terms & Conditions',
  points: [
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Please read these terms & conditions carefully. These terms & conditions shall be binding upon users and members of Ecocrew\'s website, mobile application & services.</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">The terms, guidelines, privacy policy, and other documents are made available from time to time. In the case of any conflict between these terms or documents, the term will have an overriding effect. This agreement sets out the legally binding agreement between the users and ecocrew. Ecocrew is a platform where business entities facilitate the sale of paper, plastic, metal & electronic scrap materials. Ecocrew understands the importance of privacy and also the importance of maintaining the confidentiality of personal information. Our Privacy Policy is applied to all the products and services which are being provided by us, and also sets out how we may collect, disclose and use the personal information (name, address, localization, income, etc.) of users. Users may use our services and products via Mobile Application and/or Website. By using our platform, you hereby consent to our Privacy policy and agree to its Terms and conditions. Any attempted transfer or assignment in violation shall be null or void.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Acceptance of Terms of Use:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">By using our mobile application or by browsing our website you are agreeing or accepting the terms, as amended from time to time with or without the notice. This website is owned and operated by Ecocrew and it reserves the right to modify or discontinue, temporarily or permanently at any time with or without notice. You agree that the website or mobile application shall not be liable to you or to any third party for any suspension or discontinuance of the services. Ecocrew or the website management may modify these terms and conditions from time to time and these changes would be reflected on the website and mobile application with the updated version of the terms or also may reflect in applications or to you via email and you agree to be bound to the changes of these terms when you use our website or website services. When you register an account on our mobile application and upload, submit, and enter any information then you shall be deemed to have agreed to and understand the terms. The website also uses cookies and by using the website you agree and give us consent for the use of cookies in accordance with the terms of the privacy policy.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">IF YOU DO NOT AGREE TO THESE TERMS OF USE, THEN YOU MAY NOT USE THE WEBSITE/MOBILE APPLICATION.</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew is operated in the scrap industry which means that it deals in location, transportation, commerce, treatment, recycling, and exploitation of the scrap materials such as metal, plastic, paper, and e-waste among others. It provides its visitors an online platform that allows the users to sell directly and execute deals that are offered by Ecocrew from time to time. Registered users can see their profiles & past performances information which the mobile application allows. This application provides an e-commerce platform for users for scrap transactions For our pickup service, you must provide your accurate information like name, address, mobile number, etc. Your pickup will be held on the scheduled date as provided by you while submitting the request. You can reschedule or cancel your pickup request at any time after submitting your request. The rate of all materials is fixed as mentioned on our price list. For the rates of other materials that are not listed on the list then you can contact us. If there are any unforeseen circumstances, we can also reschedule your pickup request to another working day.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">The obligation of Ecocrew:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew is a service-based platform, the sole purpose of which is to provide a space, where the seller of the products related to the scrap industry may interact and strike a deal of sale. Ecocrew shall not have absolute liabilities, responsibilities, or obligations with regards to any item, sold through the website.</p>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew will not bring about any obligation of all nature emerging out of any transaction made by the seller through the application in the sale of any item</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Account Registration:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">In order to use our services, you will be required to register an account. At the time of registration of an account, the user will be asked to complete the registration form which shall require you to provide personal information. You warrant all activities that occur under your account (any product information, clicking to accept any terms & conditions, or making any payment for any services) will be deemed to have been authorised by you as a user, hence you warrant to have full authority for the associated disclosure. You represent that you have full authority to accept these terms, to grant any licence and authorization, and to perform any of your obligations, you also undertake the use of the website and its services for personal purposes only. You should not allow another person to use your account. You should inform us immediately at the time of unauthorised access of your account. You can write us at: support@ecocrew.com</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Cancellation Policy for Pickups:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Accepting or cancelling the scrap pick-up service depends upon whether the services are approachable to the user or not and whether the service boy is picking up the scrap from the location which is accessible. Ecocrew has its rights in which it can accept or refuse the request initiated by the seller. A seller can also start the request or cancel the request as per their requirements and for this, no charges will be applicable. Once the service boy reaches the location and then pays for the scrap being done by the service person then the seller cannot cancel the request and cannot ask for the products & goods back. As per the Indian laws, illegal trades or activities are not allowed, if any activity takes place then strict action can be taken as per the court of law.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">User IDs-Passwords and Account deletion:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">During registration the data or personal information we collect is subject to the terms of our Privacy Policy. We may suspend, cancel or deactivate your account at any time in the sole discretion without notice as well as any other explanation. You may also cancel your account on the website by emailing us.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Effect of Breach by User:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">If any factual breach by any user for any cause, Ecocrew shall have the right to impose a penalty, restrict, refuse or ban any and all current or future use of any other service provided by Ecocrew.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Trademarks:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">The website, mobile a its logos, and its other registered trademarks belong to the company i.e; Ecocrew. Ecocrew, the website, the mobile application and the management give no permission to you for the use of these trademarks and such use may constitute an infringement of Intellectual Property Rights.</p>',
    '</div>',
    '<div class="policiesDiv pt-6 gap-4 md:gap-6 md:pt-10">',
    '<h2 class="text-large leading-5 md:leading-8">Amendments:</h2>',
    '<p class="text-darkLow text-ecoStore leading-5">Ecocrew hereby reserves the right to update, modify, change, amend, terminate or discontinue the Website, the terms, and policy at any time and at its sole and final discretion. Ecocrew may change the website\'s and/or mobile application\'s functionalities and applicable changes at any time. Any changes to these terms will be displayed on the website and we may also notify you through the website or by email. Your use of our services after the effective date of any update either by an account registration or simple use- thereby indicates your acceptance thereof.</p>',
    '</div>',
  ].join(''),
};
